#!/usr/bin/env python3
"""
One-shot migration: legacy 46-MT-Server-Login-Detect/monitoring.db → new login_ip.db.

What it moves
-------------
- `monitored_accounts` rows (watchlist of accounts to alert on)
- `login_history` rows (if any) — legacy DB is typically empty; this handles
  the rare case where a partial history exists.

JSON analysis caches are NOT moved here — they're regenerated by
`scripts/backfill_login_ip.py` and live under `data/login_ip/YYYYMMDD/`.

Idempotency
-----------
Both tables use INSERT OR IGNORE on unique constraints, so re-running is safe:
- `monitored_accounts.account_id` is UNIQUE → same watchlist entry won't duplicate
- `login_history (account_id, ip, date, server)` is UNIQUE → same login won't duplicate

Usage
-----
    cd /opt/myproject/New-IT-System/backend
    source .venv/bin/activate
    python scripts/migrate_login_ip_from_legacy.py

    # Use a non-default source path:
    python scripts/migrate_login_ip_from_legacy.py \\
        --legacy-db /path/to/monitoring.db
"""

from __future__ import annotations

import argparse
import logging
import sqlite3
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
# Make `from app.core.login_ip_db import ...` work when invoked as a script.
sys.path.insert(0, str(BACKEND_ROOT))

from app.core.login_ip_db import (  # noqa: E402
    add_login_history,
    add_monitored_accounts,
    get_db_stats,
    init_login_ip_db,
)

DEFAULT_LEGACY_DB = Path("/opt/myproject/log_analysis/46-MT-Server-Login-Detect/monitoring.db")

logger = logging.getLogger("migrate_login_ip")


def _read_legacy(legacy_path: Path) -> tuple[list[tuple], list[tuple]]:
    """Return (monitored_rows, login_history_rows) from the legacy DB.

    Raises FileNotFoundError if the legacy DB is missing — we want a loud
    failure rather than silently producing an empty new DB.
    """
    if not legacy_path.exists():
        raise FileNotFoundError(f"Legacy DB not found: {legacy_path}")

    with sqlite3.connect(str(legacy_path)) as conn:
        conn.row_factory = sqlite3.Row

        monitored_rows = [
            (r["account_id"], r["server_name"], r["remarks"])
            for r in conn.execute(
                "SELECT account_id, server_name, remarks FROM monitored_accounts"
            )
        ]

        history_rows = [
            (r["account_id"], r["ip_address"], r["login_date"], r["server_name"])
            for r in conn.execute(
                "SELECT account_id, ip_address, login_date, server_name FROM login_history"
            )
        ]

    return monitored_rows, history_rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument(
        "--legacy-db",
        type=Path,
        default=DEFAULT_LEGACY_DB,
        help=f"Path to legacy monitoring.db (default: {DEFAULT_LEGACY_DB})",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="DEBUG-level logs.")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    logger.info("=" * 70)
    logger.info("Migrate legacy Login IP DB")
    logger.info("  source: %s", args.legacy_db)
    logger.info("=" * 70)

    # 1. Make sure the new DB exists before we try to write into it.
    init_login_ip_db()

    # 2. Read the legacy DB.
    try:
        monitored, history = _read_legacy(args.legacy_db)
    except FileNotFoundError as exc:
        logger.error(str(exc))
        return 2

    logger.info("legacy read: %d monitored_accounts, %d login_history rows",
                len(monitored), len(history))

    # 3. Write into the new DB (idempotent via INSERT OR IGNORE inside helpers).
    inserted_watch = add_monitored_accounts(monitored)
    inserted_hist = add_login_history(history) if history else 0

    # 4. Print post-migration state so you can verify at a glance.
    stats = get_db_stats()
    logger.info("")
    logger.info("=" * 70)
    logger.info("Migration done. New DB: %s", stats["db_path"])
    logger.info("  monitored_accounts: %d total (%d newly inserted)",
                stats["monitored_accounts"], inserted_watch)
    logger.info("  login_history:      %d total (%d newly inserted)",
                stats["login_history_rows"], inserted_hist)
    if stats["login_date_min"]:
        logger.info("  login_date range:   %s -> %s",
                    stats["login_date_min"], stats["login_date_max"])
    logger.info("=" * 70)
    logger.info("")
    logger.info("Next step: run populate_login_history_from_json.py to backfill"
                " login_history from the 14 days of analysis JSONs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
